'use strict';

/**
 * The market tables and exposure arithmetic from the legacy place-bet handler.
 *
 * Copied VERBATIM out of `legacy/sportsmain/API/controller.js` — the lists,
 * the regexes, the helper functions and the float maths, unchanged. They were
 * declared INSIDE `placeBet`, so every request rebuilt an 830-entry array and
 * four more besides; module scope is the only difference, and it is not a
 * behavioural one.
 *
 * @legacy legacy/sportsmain/API/controller.js:409-1443
 */

// ── legacy controller.js:54-58 ────────────────────────────────────────────

function normalizeOdds(odds) {
    if (odds > 100) return Math.floor(((odds / 100) + 1) * 100) / 100;
    if (odds < 100) return Math.floor((1 + (odds / 100)) * 100) / 100;
    return 2.0;
}

// ── legacy controller.js:409-1240 ─────────────────────────────────────────
const marketsfornonfancy = [
    'Game Winner 1/2',
    'OVER_UNDER_55',
    'OVER_UNDER_45',
    'OVER_UNDER_35',
    'OVER_UNDER_25',
    'OVER_UNDER_15',
    'OVER_UNDER_05',
    'OVER_UNDER_10',

    '2nd Period Winner',
    '1st Period Winner',
    '3rd Period Winner',
    'Both Teams To Score',
    'DRAW_NO_BET',
    'Draw No Bet',

    'HALF_TIME',
    'Match Time Result 70:00',
    'Match Time Result 10:00',
    'Match Time Result 30:00',
    'Match Time Result 20:00',
    'Match Time Result 40:00',
    'Match Time Result 60:00',
    'Match Time Result 50:00',
    'Match Time Result 70:00',
    'Match Time Result 80:00',
    'Match Time Result 90:00',
    'Game Winner 1/1',
    'Game Winner 1/2',
    'Game Winner 1/3',
    'Game Winner 1/4',
    'Game Winner 1/5',
    'Game Winner 1/6',
    'Game Winner 1/7',
    'Game Winner 1/8',
    'Game Winner 1/9',
    'Game Winner 1/10',
    'Game Winner 1/11',
    'Game Winner 1/12',
    'Game Winner 1/13',
    'Game Winner 1/14',
    'Game Winner 1/15',
    'Game Winner 1/16',
    'Game Winner 1/17',
    'Game Winner 1/18',
    'Game Winner 1/19',
    'Game Winner 1/20',
    'Game Winner 2/2',
    'Game Winner 2/3',
    'Game Winner 2/4',
    'Game Winner 2/5',
    'Game Winner 2/6',
    'Game Winner 2/7',
    'Game Winner 2/8',
    'Game Winner 2/9',
    'Game Winner 2/10',
    'Game Winner 2/11',
    'Game Winner 2/12',
    'Game Winner 2/13',
    'Game Winner 2/14',
    'Game Winner 2/15',
    'Game Winner 2/16',
    'Game Winner 2/17',
    'Game Winner 2/18',
    'Game Winner 2/19',
    'Game Winner 2/20',
    'Game Winner 3/1',
    'Game Winner 3/2',
    'Game Winner 3/3',
    'Game Winner 3/4',
    'Game Winner 3/5',
    'Game Winner 3/6',
    'Game Winner 3/7',
    'Game Winner 3/8',
    'Game Winner 3/9',
    'Game Winner 3/10',
    'Game Winner 3/11',
    'Game Winner 3/12',
    'Game Winner 3/13',
    'Game Winner 3/14',
    'Game Winner 3/15',
    'Game Winner 3/16',
    'Game Winner 3/17',
    'Game Winner 3/18',
    'Game Winner 3/19',
    'Game Winner 3/20',
    'Game Winner 4/1',
    'Game Winner 4/2',
    'Game Winner 4/3',
    'Game Winner 4/4',
    'Game Winner 4/5',
    'Game Winner 4/6',
    'Game Winner 4/7',
    'Game Winner 4/8',
    'Game Winner 4/9',
    'Game Winner 4/10',
    'Game Winner 4/11',
    'Game Winner 4/12',
    'Game Winner 4/13',
    'Game Winner 4/14',
    'Game Winner 4/15',
    'Game Winner 4/16',
    'Game Winner 4/17',
    'Game Winner 4/18',
    'Game Winner 4/19',
    'Game Winner 4/20',
    'Game Winner 5/1',
    'Game Winner 5/2',
    'Game Winner 5/3',
    'Game Winner 5/4',
    'Game Winner 5/5',
    'Game Winner 5/6',
    'Game Winner 5/7',
    'Game Winner 5/8',
    'Game Winner 5/9',
    'Game Winner 5/10',
    'Game Winner 5/11',
    'Game Winner 5/12',
    'Game Winner 5/13',
    'Game Winner 5/14',
    'Game Winner 5/15',
    'Game Winner 5/16',
    'Game Winner 5/17',
    'Game Winner 5/18',
    'Game Winner 5/19',
    'Game Winner 5/20',
    'Game Winner 6/1',
    'Game Winner 6/2',
    'Game Winner 6/3',
    'Game Winner 6/4',
    'Game Winner 6/5',
    'Game Winner 6/6',
    'Game Winner 6/7',
    'Game Winner 6/8',
    'Game Winner 6/9',
    'Game Winner 6/10',
    'Game Winner 7/1',
    'Game Winner 7/2',
    'Game Winner 7/3',
    'Game Winner 7/4',
    'Game Winner 7/5',
    'Game Winner 7/6',
    'Game Winner 7/7',
    'Game Winner 2/7',
    'Game Winner 3/7',
    'Game Winner 4/7',
    'Game Winner 5/7',
    'Game Winner 6/7',
    'Game Winner 7/7',
    '1st Set Winner Home/Away',
    '2nd Set Winner Home/Away',
    '3rd Set Winner Home/Away',
    '4th Set Winner Home/Away',
    '5th Set Winner Home/Away',
    '1st Set Winner',
    '2nd Set Winner',
    '3rd Set Winner',
    '4th Set Winner',
    '5th Set Winner',
    '6th Set Winner',
    '1st Half Winner',
    '2nd Half Winner',
    '3rd Half Winner',
    '4th Half Winner',
    '5th Half Winner',
    '6th Half Winner',
    '1st Quarter Winner',
    '2nd Quarter Winner',
    '3rd Quarter Winner',
    '4th Quarter Winner',
    '5th Quarter Winner',
    '6th Quarter Winner',
    '1st Set Race To 1.0',
    '1st Set Race To 2.0',
    '1st Set Race To 3.0',
    '1st Set Race To 4.0',
    '1st Set Race To 5.0',
    '1st Set Race To 6.0',
    '1st Set Race To 7.0',
    '1st Set Race To 8.0',
    '1st Set Race To 9.0',
    '1st Set Race To 10.0',
    '1st Set Race To 11.0',
    '1st Set Race To 12.0',
    '1st Set Race To 13.0',
    '1st Set Race To 14.0',
    '1st Set Race To 15.0',
    '2nd Set Race To 1.0',
    '2nd Set Race To 2.0',
    '2nd Set Race To 3.0',
    '2nd Set Race To 4.0',
    '2nd Set Race To 5.0',
    '2nd Set Race To 6.0',
    '2nd Set Race To 7.0',
    '2nd Set Race To 8.0',
    '2nd Set Race To 9.0',
    '2nd Set Race To 10.0',
    '2nd Set Race To 11.0',
    '2nd Set Race To 12.0',
    '2nd Set Race To 13.0',
    '2nd Set Race To 14.0',
    '2nd Set Race To 15.0',
    '3rd Set Race To 1.0',
    '3rd Set Race To 2.0',
    '3rd Set Race To 3.0',
    '3rd Set Race To 4.0',
    '3rd Set Race To 5.0',
    '3rd Set Race To 6.0',
    '3rd Set Race To 7.0',
    '3rd Set Race To 8.0',
    '3rd Set Race To 9.0',
    '3rd Set Race To 10.0',
    '3rd Set Race To 11.0',
    '3rd Set Race To 12.0',
    '3rd Set Race To 13.0',
    '3rd Set Race To 14.0',
    '3rd Set Race To 15.0',
    '4th Set Race To 1.0',
    '4th Set Race To 2.0',
    '4th Set Race To 3.0',
    '4th Set Race To 4.0',
    '4th Set Race To 5.0',
    '4th Set Race To 6.0',
    '4th Set Race To 7.0',
    '4th Set Race To 8.0',
    '4th Set Race To 9.0',
    '4th Set Race To 10.0',
    '4th Set Race To 11.0',
    '4th Set Race To 12.0',
    '4th Set Race To 13.0',
    '4th Set Race To 14.0',
    '4th Set Race To 15.0',
    'Point Winner 1/1/1',
    'Point Winner 1/1/1',
    'Point Winner 1/1/2',
    'Point Winner 1/1/3',
    'Point Winner 1/1/4',
    'Point Winner 1/1/5',
    'Point Winner 1/1/6',
    'Point Winner 1/1/7',
    'Point Winner 1/1/8',
    'Point Winner 1/1/9',
    'Point Winner 1/1/10',
    'Point Winner 1/1/11',
    'Point Winner 1/1/12',
    'Point Winner 1/1/13',
    'Point Winner 1/1/14',
    'Point Winner 1/1/15',
    'Point Winner 1/1/16',
    'Point Winner 1/1/17',
    'Point Winner 1/1/18',
    'Point Winner 1/1/19',
    'Point Winner 1/1/20',
    'Point Winner 1/2/1',
    'Point Winner 1/2/2',
    'Point Winner 1/2/3',
    'Point Winner 1/2/4',
    'Point Winner 1/2/5',
    'Point Winner 1/2/6',
    'Point Winner 1/2/7',
    'Point Winner 1/2/8',
    'Point Winner 1/2/9',
    'Point Winner 1/2/10',
    'Point Winner 1/2/11',
    'Point Winner 1/2/12',
    'Point Winner 1/2/13',
    'Point Winner 1/2/14',
    'Point Winner 1/2/15',
    'Point Winner 1/2/16',
    'Point Winner 1/2/17',
    'Point Winner 1/2/18',
    'Point Winner 1/2/19',
    'Point Winner 1/2/20',
    'Point Winner 1/3/1',
    'Point Winner 1/3/2',
    'Point Winner 1/3/3',
    'Point Winner 1/3/4',
    'Point Winner 1/3/5',
    'Point Winner 1/3/6',
    'Point Winner 1/3/7',
    'Point Winner 1/3/8',
    'Point Winner 1/3/9',
    'Point Winner 1/3/10',
    'Point Winner 1/3/11',
    'Point Winner 1/3/12',
    'Point Winner 1/3/13',
    'Point Winner 1/3/14',
    'Point Winner 1/3/15',
    'Point Winner 1/3/16',
    'Point Winner 1/3/17',
    'Point Winner 1/3/18',
    'Point Winner 1/3/19',
    'Point Winner 1/3/20',
    'Point Winner 1/4/1',
    'Point Winner 1/4/2',
    'Point Winner 1/4/3',
    'Point Winner 1/4/4',
    'Point Winner 1/4/5',
    'Point Winner 1/4/6',
    'Point Winner 1/4/7',
    'Point Winner 1/4/8',
    'Point Winner 1/4/9',
    'Point Winner 1/5/1',
    'Point Winner 1/5/2',
    'Point Winner 1/5/3',
    'Point Winner 1/5/4',
    'Point Winner 1/5/5',
    'Point Winner 1/5/6',
    'Point Winner 1/5/7',
    'Point Winner 1/5/8',
    'Point Winner 1/5/9',
    'Point Winner 1/6/1',
    'Point Winner 1/6/2',
    'Point Winner 1/6/3',
    'Point Winner 1/6/4',
    'Point Winner 1/6/5',
    'Point Winner 1/6/6',
    'Point Winner 1/6/7',
    'Point Winner 1/6/8',
    'Point Winner 1/6/9',
    'Point Winner 1/7/1',
    'Point Winner 1/7/2',
    'Point Winner 1/7/3',
    'Point Winner 1/7/4',
    'Point Winner 1/7/5',
    'Point Winner 1/7/6',
    'Point Winner 1/7/7',
    'Point Winner 1/7/8',
    'Point Winner 1/7/9',
    'Point Winner 1/8/1',
    'Point Winner 1/8/2',
    'Point Winner 1/8/3',
    'Point Winner 1/8/4',
    'Point Winner 1/8/5',
    'Point Winner 1/8/6',
    'Point Winner 1/8/7',
    'Point Winner 1/8/8',
    'Point Winner 1/8/9',
    'Point Winner 1/9/1',
    'Point Winner 1/9/2',
    'Point Winner 1/9/3',
    'Point Winner 1/9/4',
    'Point Winner 1/9/5',
    'Point Winner 1/9/6',
    'Point Winner 1/9/7',
    'Point Winner 1/9/8',
    'Point Winner 1/9/9',


    'Point Winner 2/1/1',
    'Point Winner 2/1/2',
    'Point Winner 2/1/3',
    'Point Winner 2/1/4',
    'Point Winner 2/1/5',
    'Point Winner 2/1/6',
    'Point Winner 2/1/7',
    'Point Winner 2/1/8',
    'Point Winner 2/1/9',
    'Point Winner 2/2/1',
    'Point Winner 2/2/2',
    'Point Winner 2/2/3',
    'Point Winner 2/2/4',
    'Point Winner 2/2/5',
    'Point Winner 2/2/6',
    'Point Winner 2/2/7',
    'Point Winner 2/2/8',
    'Point Winner 2/2/9',
    'Point Winner 2/3/1',
    'Point Winner 2/3/2',
    'Point Winner 2/3/3',
    'Point Winner 2/3/4',
    'Point Winner 2/3/5',
    'Point Winner 2/3/6',
    'Point Winner 2/3/7',
    'Point Winner 2/3/8',
    'Point Winner 2/3/9',
    'Point Winner 2/4/1',
    'Point Winner 2/4/2',
    'Point Winner 2/4/3',
    'Point Winner 2/4/4',
    'Point Winner 2/4/5',
    'Point Winner 2/4/6',
    'Point Winner 2/4/7',
    'Point Winner 2/4/8',
    'Point Winner 2/4/9',
    'Point Winner 2/5/1',
    'Point Winner 2/5/2',
    'Point Winner 2/5/3',
    'Point Winner 2/5/4',
    'Point Winner 2/5/5',
    'Point Winner 2/5/6',
    'Point Winner 2/5/7',
    'Point Winner 2/5/8',
    'Point Winner 2/5/9',
    'Point Winner 2/6/1',
    'Point Winner 2/6/2',
    'Point Winner 2/6/3',
    'Point Winner 2/6/4',
    'Point Winner 2/6/5',
    'Point Winner 2/6/6',
    'Point Winner 2/6/7',
    'Point Winner 2/6/8',
    'Point Winner 2/6/9',
    'Point Winner 2/7/1',
    'Point Winner 2/7/2',
    'Point Winner 2/7/3',
    'Point Winner 2/7/4',
    'Point Winner 2/7/5',
    'Point Winner 2/7/6',
    'Point Winner 2/7/7',
    'Point Winner 2/7/8',
    'Point Winner 2/7/9',
    'Point Winner 2/8/1',
    'Point Winner 2/8/2',
    'Point Winner 2/8/3',
    'Point Winner 2/8/4',
    'Point Winner 2/8/5',
    'Point Winner 2/8/6',
    'Point Winner 2/8/7',
    'Point Winner 2/8/8',
    'Point Winner 2/8/9',
    'Point Winner 2/9/1',
    'Point Winner 2/9/2',
    'Point Winner 2/9/3',
    'Point Winner 2/9/4',
    'Point Winner 2/9/5',
    'Point Winner 2/9/6',
    'Point Winner 2/9/7',
    'Point Winner 2/9/8',
    'Point Winner 2/9/9',

    'Point Winner 3/1/1',
    'Point Winner 3/1/2',
    'Point Winner 3/1/3',
    'Point Winner 3/1/4',
    'Point Winner 3/1/5',
    'Point Winner 3/1/6',
    'Point Winner 3/1/7',
    'Point Winner 3/1/8',
    'Point Winner 3/1/9',
    'Point Winner 3/2/1',
    'Point Winner 3/2/2',
    'Point Winner 3/2/3',
    'Point Winner 3/2/4',
    'Point Winner 3/2/5',
    'Point Winner 3/2/6',
    'Point Winner 3/2/7',
    'Point Winner 3/2/8',
    'Point Winner 3/2/9',
    'Point Winner 3/3/1',
    'Point Winner 3/3/2',
    'Point Winner 3/3/3',
    'Point Winner 3/3/4',
    'Point Winner 3/3/5',
    'Point Winner 3/3/6',
    'Point Winner 3/3/7',
    'Point Winner 3/3/8',
    'Point Winner 3/3/9',
    'Point Winner 3/4/1',
    'Point Winner 3/4/2',
    'Point Winner 3/4/3',
    'Point Winner 3/4/4',
    'Point Winner 3/4/5',
    'Point Winner 3/4/6',
    'Point Winner 3/4/7',
    'Point Winner 3/4/8',
    'Point Winner 3/4/9',
    'Point Winner 3/5/1',
    'Point Winner 3/5/2',
    'Point Winner 3/5/3',
    'Point Winner 3/5/4',
    'Point Winner 3/5/5',
    'Point Winner 3/5/6',
    'Point Winner 3/5/7',
    'Point Winner 3/5/8',
    'Point Winner 3/5/9',
    'Point Winner 3/6/1',
    'Point Winner 3/6/2',
    'Point Winner 3/6/3',
    'Point Winner 3/6/4',
    'Point Winner 3/6/5',
    'Point Winner 3/6/6',
    'Point Winner 3/6/7',
    'Point Winner 3/6/8',
    'Point Winner 3/6/9',
    'Point Winner 3/7/1',
    'Point Winner 3/7/2',
    'Point Winner 3/7/3',
    'Point Winner 3/7/4',
    'Point Winner 3/7/5',
    'Point Winner 3/7/6',
    'Point Winner 3/7/7',
    'Point Winner 3/7/8',
    'Point Winner 3/7/9',
    'Point Winner 3/8/1',
    'Point Winner 3/8/2',
    'Point Winner 3/8/3',
    'Point Winner 3/8/4',
    'Point Winner 3/8/5',
    'Point Winner 3/8/6',
    'Point Winner 3/8/7',
    'Point Winner 3/8/8',
    'Point Winner 3/8/9',
    'Point Winner 3/9/1',
    'Point Winner 3/9/2',
    'Point Winner 3/9/3',
    'Point Winner 3/9/4',
    'Point Winner 3/9/5',
    'Point Winner 3/9/6',
    'Point Winner 3/9/7',
    'Point Winner 3/9/8',
    'Point Winner 3/9/9',

    'Point Winner 4/1/1',
    'Point Winner 4/1/2',
    'Point Winner 4/1/3',
    'Point Winner 4/1/4',
    'Point Winner 4/1/5',
    'Point Winner 4/1/6',
    'Point Winner 4/1/7',
    'Point Winner 4/1/8',
    'Point Winner 4/1/9',
    'Point Winner 4/2/1',
    'Point Winner 4/2/2',
    'Point Winner 4/2/3',
    'Point Winner 4/2/4',
    'Point Winner 4/2/5',
    'Point Winner 4/2/6',
    'Point Winner 4/2/7',
    'Point Winner 4/2/8',
    'Point Winner 4/2/9',
    'Point Winner 4/3/1',
    'Point Winner 4/3/2',
    'Point Winner 4/3/3',
    'Point Winner 4/3/4',
    'Point Winner 4/3/5',
    'Point Winner 4/3/6',
    'Point Winner 4/3/7',
    'Point Winner 4/3/8',
    'Point Winner 4/3/9',
    'Point Winner 4/4/1',
    'Point Winner 4/4/2',
    'Point Winner 4/4/3',
    'Point Winner 4/4/4',
    'Point Winner 4/4/5',
    'Point Winner 4/4/6',
    'Point Winner 4/4/7',
    'Point Winner 4/4/8',
    'Point Winner 4/4/9',
    'Point Winner 4/5/1',
    'Point Winner 4/5/2',
    'Point Winner 4/5/3',
    'Point Winner 4/5/4',
    'Point Winner 4/5/5',
    'Point Winner 4/5/6',
    'Point Winner 4/5/7',
    'Point Winner 4/5/8',
    'Point Winner 4/5/9',
    'Point Winner 4/6/1',
    'Point Winner 4/6/2',
    'Point Winner 4/6/3',
    'Point Winner 4/6/4',
    'Point Winner 4/6/5',
    'Point Winner 4/6/6',
    'Point Winner 4/6/7',
    'Point Winner 4/6/8',
    'Point Winner 4/6/9',
    'Point Winner 4/7/1',
    'Point Winner 4/7/2',
    'Point Winner 4/7/3',
    'Point Winner 4/7/4',
    'Point Winner 4/7/5',
    'Point Winner 4/7/6',
    'Point Winner 4/7/7',
    'Point Winner 4/7/8',
    'Point Winner 4/7/9',
    'Point Winner 4/8/1',
    'Point Winner 4/8/2',
    'Point Winner 4/8/3',
    'Point Winner 4/8/4',
    'Point Winner 4/8/5',
    'Point Winner 4/8/6',
    'Point Winner 4/8/7',
    'Point Winner 4/8/8',
    'Point Winner 4/8/9',
    'Point Winner 4/9/1',
    'Point Winner 4/9/2',
    'Point Winner 4/9/3',
    'Point Winner 4/9/4',
    'Point Winner 4/9/5',
    'Point Winner 4/9/6',
    'Point Winner 4/9/7',
    'Point Winner 4/9/8',
    'Point Winner 4/9/9',


    'Under/Over 5.5',
    'Under/Over 0.5',
    'Under/Over 1.5',
    'Under/Over 2.5',
    'Under/Over 3.5',
    'Under/Over 4.5',
    'Under/Over 6.5',
    // 'BM 1st Set Winner',
    // 'BM 2nd Set Winner',
    // 'BM 3rd Set Winner',
    // 'BM 4th Set Winner',
    // 'BM 5th Set Winner',
    '1st Set Race To 10.0',
    '1st Set Race To 9.0',
    '1st Set Race To 8.0',
    '1st Set Race To 7.0',
    '1st Set Race To 6.0',
    '1st Set Race To 5.0',
    '1st Set Race To 4.0',
    '1st Set Race To 3.0',
    '1st Set Race To 2.0',
    '1st Set Race To 1.0',
    '2nd Set Race To 10.0',
    '2nd Set Race To 9.0',
    '2nd Set Race To 8.0',
    '2nd Set Race To 7.0',
    '2nd Set Race To 6.0',
    '2nd Set Race To 5.0',
    '2nd Set Race To 4.0',
    '2nd Set Race To 3.0',
    '2nd Set Race To 2.0',
    '2nd Set Race To 1.0',
    '3rd Set Race To 10.0',
    '3rd Set Race To 9.0',
    '3rd Set Race To 8.0',
    '3rd Set Race To 7.0',
    '3rd Set Race To 6.0',
    '3rd Set Race To 5.0',
    '3rd Set Race To 4.0',
    '3rd Set Race To 3.0',
    '3rd Set Race To 2.0',
    '3rd Set Race To 1.0',
    '4th Set Race To 10.0',
    '4th Set Race To 9.0',
    '4th Set Race To 8.0',
    '4th Set Race To 7.0',
    '4th Set Race To 6.0',
    '4th Set Race To 5.0',
    '4th Set Race To 4.0',
    '4th Set Race To 3.0',
    '4th Set Race To 2.0',
    '4th Set Race To 1.0',
    '5th Set Race To 4.0',
    '5th Set Race To 3.0',
    '5th Set Race To 2.0',
    '5th Set Race To 1.0',
    'Total Tie Break in the Match 0.5',
    'Total Tie Break in the Match 1.0',
    'Total Tie Break in the Match 1.5',
    'Total Tie Break in the Match 2.0',
    'Total Tie Break in the Match 2.5',
    'Total Tie Break in the Match 3.5',
    'Game To Deuce 1/1',
    'Game To Deuce 1/2',
    'Game To Deuce 1/3',
    'Game To Deuce 1/4',
    'Game To Deuce 1/5',
    'Game To Deuce 1/6',
    'Game To Deuce 1/7',
    'Game To Deuce 1/8',
    'Game To Deuce 1/9',
    'Game To Deuce 1/10',
    'Game To Deuce 1/11',
    'Game To Deuce 1/12',
    'Game To Deuce 1/13',
    'Game To Deuce 1/14',
    'Game To Deuce 1/15',
    'Game To Deuce 1/16',
    'Game To Deuce 1/17',
    'Game To Deuce 1/18',
    'Game To Deuce 1/19',
    'Game To Deuce 1/20',
    'Game To Deuce 2/1',
    'Game To Deuce 2/2',
    'Game To Deuce 2/3',
    'Game To Deuce 2/4',
    'Game To Deuce 2/5',
    'Game To Deuce 2/6',
    'Game To Deuce 2/7',
    'Game To Deuce 2/8',
    'Game To Deuce 2/9',
    'Game To Deuce 2/10',
    'Game To Deuce 2/11',
    'Game To Deuce 2/12',
    'Game To Deuce 2/13',
    'Game To Deuce 2/14',
    'Game To Deuce 2/15',
    'Game To Deuce 2/16',
    'Game To Deuce 2/17',
    'Game To Deuce 2/18',
    'Game To Deuce 2/19',
    'Game To Deuce 2/20',

    'Game To Deuce 3/1',
    'Game To Deuce 3/2',
    'Game To Deuce 3/3',
    'Game To Deuce 3/4',
    'Game To Deuce 3/5',
    'Game To Deuce 3/6',
    'Game To Deuce 3/7',
    'Game To Deuce 3/8',
    'Game To Deuce 3/9',
    'Game To Deuce 3/10',
    'Game To Deuce 3/11',
    'Game To Deuce 3/12',
    'Game To Deuce 3/13',
    'Game To Deuce 3/14',
    'Game To Deuce 3/15',
    'Game To Deuce 3/16',
    'Game To Deuce 3/17',
    'Game To Deuce 3/18',
    'Game To Deuce 3/19',
    'Game To Deuce 3/20',

    'Game To Deuce 4/1',
    'Game To Deuce 4/2',
    'Game To Deuce 4/3',
    'Game To Deuce 4/4',
    'Game To Deuce 4/5',
    'Game To Deuce 4/6',
    'Game To Deuce 4/7',
    'Game To Deuce 4/8',
    'Game To Deuce 4/9',
    'Game To Deuce 4/10',
    'Game To Deuce 4/11',
    'Game To Deuce 4/12',
    'Game To Deuce 4/13',
    'Game To Deuce 4/14',
    'Game To Deuce 4/15',
    'Game To Deuce 4/16',
    'Game To Deuce 4/17',
    'Game To Deuce 4/18',
    'Game To Deuce 4/19',
    'Game To Deuce 4/20',

    'Game To Deuce 5/1',
    'Game To Deuce 5/2',
    'Game To Deuce 5/3',
    'Game To Deuce 5/4',
    'Game To Deuce 5/5',
    'Game To Deuce 5/6',
    'Game To Deuce 5/7',
    'Game To Deuce 5/8',
    'Game To Deuce 5/9',
    'Game To Deuce 5/10',
    'Game To Deuce 5/11',
    'Game To Deuce 5/12',
    'Game To Deuce 5/13',
    'Game To Deuce 5/14',
    'Game To Deuce 5/15',
    'Game To Deuce 5/16',
    'Game To Deuce 5/17',
    'Game To Deuce 5/18',
    'Game To Deuce 5/19',
    'Game To Deuce 5/20',

    'Game To Deuce 6/1',
    'Game To Deuce 6/2',
    'Game To Deuce 6/3',
    'Game To Deuce 6/4',
    'Game To Deuce 6/5',
    'Game To Deuce 6/6',
    'Game To Deuce 6/7',
    'Game To Deuce 6/8',
    'Game To Deuce 6/9',
    'Game To Deuce 6/10',
    'Game To Deuce 6/11',
    'Game To Deuce 6/12',
    'Game To Deuce 6/13',
    'Game To Deuce 6/14',
    'Game To Deuce 6/15',
    'Game To Deuce 6/16',
    'Game To Deuce 6/17',
    'Game To Deuce 6/18',
    'Game To Deuce 6/19',
    'Game To Deuce 6/20',

    'Game To Deuce 7/1',
    'Game To Deuce 7/2',
    'Game To Deuce 7/3',
    'Game To Deuce 7/4',
    'Game To Deuce 7/5',
    'Game To Deuce 7/6',
    'Game To Deuce 7/7',
    'Game To Deuce 7/8',
    'Game To Deuce 7/9',
    'Game To Deuce 7/10',

    'Game To Deuce 8/1',
    'Game To Deuce 8/2',
    'Game To Deuce 8/3',
    'Game To Deuce 8/4',
    'Game To Deuce 8/5',
    'Game To Deuce 8/6',
    'Game To Deuce 8/7',
    'Game To Deuce 8/8',
    'Game To Deuce 8/9',
    'Game To Deuce 8/10',

    'Game To Deuce 9/1',
    'Game To Deuce 9/2',
    'Game To Deuce 9/3',
    'Game To Deuce 9/4',
    'Game To Deuce 9/5',
    'Game To Deuce 9/6',
    'Game To Deuce 9/7',
    'Game To Deuce 9/8',
    'Game To Deuce 9/9',
    'Under/Over 180s 0.5',
    'Under/Over 180s 1.0',
    'Under/Over 180s 1.5',
    'Under/Over 180s 2.0',
    'Under/Over 180s 2.5',
    'Under/Over 180s 3.0',
    'Under/Over 180s 3.5',
    'Under/Over 180s 4.0',



    'Tied Match',
    "TIED_MATCH"



];

// ── legacy controller.js:1291-1340 ───────────────────────────────────────
const fixedNonFancyMarkets = [
    'OVER_UNDER_55',
    'OVER_UNDER_45',
    'OVER_UNDER_35',
    'OVER_UNDER_25',
    'OVER_UNDER_15',
    'OVER_UNDER_05',
    'OVER_UNDER_10',

    '2nd Period Winner',
    '1st Period Winner',
    '3rd Period Winner',

    'Both Teams To Score',

    'DRAW_NO_BET',
    'Draw No Bet',

    'HALF_TIME',

    '1st Set Winner Home/Away',
    '2nd Set Winner Home/Away',
    '3rd Set Winner Home/Away',
    '4th Set Winner Home/Away',
    '5th Set Winner Home/Away',

    '1st Set Winner',
    '2nd Set Winner',
    '3rd Set Winner',
    '4th Set Winner',
    '5th Set Winner',
    '6th Set Winner',

    '1st Half Winner',
    '2nd Half Winner',
    '3rd Half Winner',
    '4th Half Winner',
    '5th Half Winner',
    '6th Half Winner',

    '1st Quarter Winner',
    '2nd Quarter Winner',
    '3rd Quarter Winner',
    '4th Quarter Winner',
    '5th Quarter Winner',
    '6th Quarter Winner',

    'Tied Match',
    'TIED_MATCH'
];

// ── legacy controller.js:1241-1289 ───────────────────────────────────────
function isNonFancyMarket(market_type) {

    // 1️⃣ fixed names
    if (fixedNonFancyMarkets.includes(market_type)) {
        return true;
    }

    // 2️⃣ Game Winner X/Y
    if (/^Game Winner\s+(?:[1-9]|1\d|20)\/(?:[1-9]|1\d|20)$/.test(market_type)) {
        return true;
    }

    // 3️⃣ Match Time Result 10:00, 70:00, etc
    if (/^Match Time Result\s+\d{2}:\d{2}$/.test(market_type)) {
        return true;
    }

    // 4️⃣ Set Race To 1.0 – 15.0 (all sets)
    if (/^\d+(?:st|nd|rd|th)\s+Set Race To\s+(?:[1-9]|1[0-5])\.0$/.test(market_type)) {
        return true;
    }

    // 5️⃣ Under/Over 0.5 , 1.5 , 180s etc
    if (/^Under\/Over(?: 180s)?\s+\d+(\.\d)?$/.test(market_type)) {
        return true;
    }

    // 6️⃣ Total Tie Break in the Match X.X
    if (/^Total Tie Break in the Match\s+\d+(\.\d)?$/.test(market_type)) {
        return true;
    }

    // 7️⃣ Point Winner A/B/C
    if (/^Point Winner\s+(?:[1-9]|1\d|20)\/(?:[1-9]|1\d|20)\/(?:[1-9]|1\d|20)$/.test(market_type)) {
        return true;
    }

    // 8️⃣ Game To Deuce A/B   (your current list)
    if (/^Game To Deuce\s+(?:[1-9]|1\d|20)\/(?:[1-9]|1\d|20)$/.test(market_type)) {
        return true;
    }

    // 9️⃣ Game To Deuce A/B/C (future support – as you mentioned before)
    if (/^Game To Deuce\s+(?:[1-9]|1\d|20)\/(?:[1-9]|1\d|20)\/(?:[1-9]|1\d|20)$/.test(market_type)) {
        return true;
    }

    return false;
}

// ── legacy controller.js:1342-1368 ───────────────────────────────────────
const marketsforfancy = [
    '1st Innings 6 Overs Line',
    '2nd Innings 6 Overs Line',
    '3rd Innings 6 Overs Line',
    '1st Innings 50 Overs Line',
    '2nd Innings 50 Overs Line',
    '3rd Innings 50 Overs Line',
    '1st Innings 40 Overs Line',
    '2nd Innings 40 Overs Line',
    '3rd Innings 40 Overs Line',
    '1st Innings 30 Overs Line',
    '2nd Innings 30 Overs Line',
    '3rd Innings 30 Overs Line',
    '1st Innings 20 Overs Line',
    '2nd Innings 20 Overs Line',
    '3rd Innings 20 Overs Line',
    '1st Innings 10 Overs Line',
    '2nd Innings 10 Overs Line',
    '3rd Innings 10 Overs Line',
    'Over By Over',
    'Ball By Ball',
    'Normal',
    'khado',
    'meter',
    'fancy1',
    'oddeven'
];

// ── legacy controller.js:1369-1375 ───────────────────────────────────────
const marketsforBMfancy = [
    'BM 1st Set Winner',
    'BM 2nd Set Winner',
    'BM 3rd Set Winner',
    'BM 4th Set Winner',
    'BM 5th Set Winner',
];

// ── legacy controller.js:1376-1403 ───────────────────────────────────────
const marketforfancywithbigrunners = [
    '2ND INN 30 OVER',
    '2ND INN 35 OVER',
    '1ST INN 20 OVER',
    '2ND INN 50 OVER',
    'TOURNAMENT_WINNER',
    'Next Goal 1.0',
    'Next Goal 2.0',
    'Next Goal 3.0',
    'Next Goal 4.0',
    'Next Goal 5.0',
    'Next Goal 6.0',
    'Next Goal 7.0',
    'Next Goal 8.0',
    'Next Goal 9.0',
    'Next Goal 10.0',
    'Match Result/Both Teams to score',
    'Correct Score 1st Set',
    'Correct Score 2nd Set',
    'Correct Score 3rd Set',
    'Correct Score 4th Set',
    'Correct Score 5th Set',
    'Correct Score 6th Set',
    'HT/FT'

    // 'oddeven'

];

// ── legacy controller.js:1405-1436 ───────────────────────────────────────
function calculateRunnerExposure({
    runners,
    selectedRunner,
    stake,
    odd,
    betType,
    oldExposures = {}
}) {
    let newExposures = { ...oldExposures };

    const profit = stake * (odd - 1);
    const liability = stake * (odd - 1);

    const isBack = betType === 'back' || betType === 'yes';
    const isLay = betType === 'lay' || betType === 'no';

    for (const runner of runners) {
        const prev = oldExposures[runner] || 0;

        if (runner === selectedRunner) {
            newExposures[runner] = isBack
                ? prev + profit
                : prev - liability;
        } else {
            newExposures[runner] = isBack
                ? prev - stake
                : prev + stake;
        }
    }

    return newExposures;
}

// ── legacy controller.js:1437-1443 ───────────────────────────────────────
function isFancyMatch(gameType = '', matchList = []) {
    const normalized = gameType.toUpperCase();

    return matchList.some(item =>
        normalized.includes(item.toUpperCase())
    );
}

/**
 * The over-line markets the legacy handler enumerated inline, twice.
 *
 * @legacy controller.js:1464-1466 (equal-bhav exposure branch)
 * @legacy controller.js:1773-1775 (`size = 0` before the insert)
 *
 * Both conditions spell out the same eighteen names with '10 Overs Line' and
 * '20 Overs Line' repeated; the set is identical, so it is one list here.
 */
const OVERS_LINE_MARKETS = [
    '1st Innings 6 Overs Line', '2nd Innings 6 Overs Line', '3rd Innings 6 Overs Line',
    '1st Innings 10 Overs Line', '2nd Innings 10 Overs Line', '3rd Innings 10 Overs Line',
    '1st Innings 20 Overs Line', '2nd Innings 20 Overs Line', '3rd Innings 20 Overs Line',
    '1st Innings 30 Overs Line', '2nd Innings 30 Overs Line', '3rd Innings 30 Overs Line',
    '1st Innings 40 Overs Line', '2nd Innings 40 Overs Line', '3rd Innings 40 Overs Line',
    '1st Innings 50 Overs Line', '2nd Innings 50 Overs Line', '3rd Innings 50 Overs Line',
];

module.exports = {
    normalizeOdds,
    marketsfornonfancy,
    fixedNonFancyMarkets,
    isNonFancyMarket,
    marketsforfancy,
    marketsforBMfancy,
    marketforfancywithbigrunners,
    calculateRunnerExposure,
    isFancyMatch,
    OVERS_LINE_MARKETS,
};
