'use strict';

const crypto = require('crypto');

const { money } = require('@ibitplay/common');

const errors = require('./spinWheel.errors');
const { CODE_SOURCE, CODE_STATUS, DEPOSIT_SOURCES, CODE_LENGTH } = require('./spinWheel.constants');

/**
 * The spin wheel — a weighted draw that issues a deposit-bonus code.
 *
 * ─────────────────────────────────────────────────────────────────────────
 * THE DRAW USED `Math.random()`
 *
 * The winning slice was picked with `Math.random() * totalWeight`. V8's
 * `Math.random` is xorshift128+: fast, uniform, and completely predictable to
 * anyone who has seen a handful of outputs. Its internal state is recoverable
 * from consecutive values, after which every future draw is known in advance.
 *
 * On a gambling platform that is not a theoretical weakness. The endpoint was
 * unauthenticated and took `user_id` from the body, so an attacker could sample
 * the generator as often as they liked — spinning on throwaway accounts costs
 * nothing — and then spin for real when the state said the jackpot slice was
 * next.
 *
 * The draw here uses `crypto.randomInt`, which is not predictable from its
 * outputs. It is a one-line change and there was never a reason not to.
 *
 * ── THE OTHER TWO ────────────────────────────────────────────────────────
 *
 * The cooldown was a read-then-insert, so two simultaneous spins both passed
 * it. The claim now takes a row lock on the player's last claim, so the second
 * request waits and then sees the first.
 *
 * Redeem codes were generated by looping SELECT-until-free and then inserting,
 * which is the same race one level down. The uniqueness is now a database
 * constraint (migration 013) and a collision is retried rather than assumed
 * away.
 * ─────────────────────────────────────────────────────────────────────────
 */
class SpinWheelService {
  constructor({ models, db, logger, config }) {
    this.models = models;
    this.db = db;
    this.logger = logger;
    this.config = config;
  }

  // ══════════════════════════════════════════════════════════════════════
  //  Staff
  // ══════════════════════════════════════════════════════════════════════

  /** @legacy GET /api/spinwin/admin/config */
  async getConfig() {
    const row = await this.models.SpinWheelConfig.findOne({ order: [['id', 'ASC']], raw: true });
    return row ? this.#shapeConfig(row) : null;
  }

  /**
   * @legacy PUT /api/spinwin/admin/config
   *
   * Legacy used `INSERT ... ON CONFLICT (id) DO UPDATE` with no id in the
   * insert, so the conflict target was whatever id the sequence happened to
   * produce. On an empty table that inserts a second row; on a populated one it
   * inserts a THIRD, and every read takes `ORDER BY id LIMIT 1` — so an admin
   * changing the config could silently create a row nobody would ever read.
   */
  async updateConfig(input) {
    const existing = await this.models.SpinWheelConfig.findOne({ order: [['id', 'ASC']], raw: true });

    const patch = {
      ...(input.minDeposit !== undefined ? { min_deposit: input.minDeposit } : {}),
      ...(input.claimCooldownDays !== undefined ? { claim_cooldown_days: input.claimCooldownDays } : {}),
      ...(input.isActive !== undefined ? { is_active: input.isActive } : {}),
      ...(input.unlimitedSpin !== undefined ? { unlimited_spin: input.unlimitedSpin } : {}),
    };

    if (!existing) {
      const created = await this.models.SpinWheelConfig.create({
        min_deposit: input.minDeposit ?? '0',
        claim_cooldown_days: input.claimCooldownDays ?? 7,
        is_active: input.isActive ?? false,
        unlimited_spin: input.unlimitedSpin ?? false,
      });
      return this.#shapeConfig(created.get({ plain: true }));
    }

    await this.models.SpinWheelConfig.update(patch, { where: { id: existing.id } });
    const row = await this.models.SpinWheelConfig.findByPk(existing.id, { raw: true });
    return this.#shapeConfig(row);
  }

  /** @legacy GET /api/spinwin/admin/slices */
  async listSlices() {
    const rows = await this.models.SpinWheelSlices.findAll({ order: [['sort_order', 'ASC']], raw: true });
    return rows.map((r) => this.#shapeSlice(r, { includeWeight: true }));
  }

  /** @legacy POST /api/spinwin/admin/slices */
  async addSlice(input) {
    const row = await this.models.SpinWheelSlices.create({
      label: input.label,
      reward_pct: input.rewardPct ?? '0',
      // NOT NULL with a default at the database level; passing null explicitly
      // bypasses the default and fails the constraint.
      ...(input.color !== undefined ? { color: input.color } : {}),
      sort_order: input.sortOrder ?? 0,
      is_bad_luck: input.isBadLuck ?? false,
      weight: input.weight ?? 1,
    });
    return this.#shapeSlice(row.get({ plain: true }), { includeWeight: true });
  }

  /** @legacy PUT /api/spinwin/admin/slices/:id */
  async updateSlice({ id, ...input }) {
    const existing = await this.models.SpinWheelSlices.findByPk(id, { raw: true });
    if (!existing) throw errors.SLICE_NOT_FOUND({ id });

    await this.models.SpinWheelSlices.update(
      {
        ...(input.label !== undefined ? { label: input.label } : {}),
        ...(input.rewardPct !== undefined ? { reward_pct: input.rewardPct } : {}),
        ...(input.color !== undefined ? { color: input.color } : {}),
        ...(input.sortOrder !== undefined ? { sort_order: input.sortOrder } : {}),
        ...(input.isBadLuck !== undefined ? { is_bad_luck: input.isBadLuck } : {}),
        ...(input.weight !== undefined ? { weight: input.weight } : {}),
      },
      { where: { id } }
    );

    const row = await this.models.SpinWheelSlices.findByPk(id, { raw: true });
    return this.#shapeSlice(row, { includeWeight: true });
  }

  /**
   * @legacy PUT /api/spinwin/admin/slices-bulk
   *
   * One transaction. Legacy applied each slice in its own statement, so a
   * failure part-way left the wheel with the new weights on some slices and the
   * old ones on others — a distribution nobody chose.
   */
  async replaceSlices({ slices }) {
    return this.db.transaction(async (transaction) => {
      await this.models.SpinWheelSlices.destroy({ where: {}, transaction });

      const created = await this.models.SpinWheelSlices.bulkCreate(
        slices.map((s, index) => ({
          label: s.label,
          reward_pct: s.rewardPct ?? '0',
          ...(s.color !== undefined ? { color: s.color } : {}),
          sort_order: s.sortOrder ?? index,
          is_bad_luck: s.isBadLuck ?? false,
          weight: s.weight ?? 1,
        })),
        { transaction, returning: true }
      );

      return created.map((r) => this.#shapeSlice(r.get({ plain: true }), { includeWeight: true }));
    });
  }

  /** @legacy DELETE /api/spinwin/admin/slices/:id */
  async removeSlice({ id }) {
    const deleted = await this.models.SpinWheelSlices.destroy({ where: { id } });
    if (!deleted) throw errors.SLICE_NOT_FOUND({ id });
    return { id, deleted: true };
  }

  /**
   * @legacy GET /api/spinwin/admin/claims
   *
   * `depositAmount` and `rewardAmount` are the two columns that say what the
   * claim was WORTH — they were stored, and every other field returned, but
   * they were left out of the shape, so the admin table had a "Deposit" and a
   * "Reward" column with nothing to put in them. The player's name is joined
   * for the same reason: a claims list keyed only by numeric id cannot be read.
   */
  async listClaims({ userId, limit = 50, offset = 0 }) {
    const { rows, count } = await this.models.SpinWheelClaims.findAndCountAll({
      where: userId ? { user_id: userId } : {},
      order: [['claimed_at', 'DESC']],
      limit,
      offset,
      raw: true,
    });

    const ids = [...new Set(rows.map((r) => String(r.user_id)))];
    const users = ids.length
      ? await this.models.Users.findAll({ where: { id: ids }, attributes: ['id', 'name'], raw: true })
      : [];
    const nameById = new Map(users.map((u) => [String(u.id), u.name ?? null]));

    return {
      total: count,
      rows: rows.map((r) => ({
        id: r.id,
        userId: r.user_id,
        username: nameById.get(String(r.user_id)) ?? null,
        // Decimal strings, like every other money field on the wire.
        depositAmount: money.fromStored(r.deposit_amount ?? '0', { field: 'depositAmount' }),
        rewardAmount: money.fromStored(r.reward_amount ?? '0', { field: 'rewardAmount' }),
        sliceLabel: r.slice_label,
        redeemCode: r.redeem_code,
        claimedAt: r.claimed_at,
      })),
    };
  }

  // ══════════════════════════════════════════════════════════════════════
  //  Players
  // ══════════════════════════════════════════════════════════════════════

  /**
   * @legacy GET /api/spinwin/slices
   *
   * What the wheel looks like. Public, because the front end draws it before
   * anyone signs in.
   *
   * WITHOUT the weights — legacy got this right and it is worth keeping right.
   * Publishing the weights tells a player the exact odds of each slice, which
   * is both commercially sensitive and, combined with the old `Math.random`
   * draw, everything needed to predict a spin.
   */
  async publicSlices() {
    const config = await this.getConfig();
    if (!config?.isActive) return { slices: [], disabled: true };

    const rows = await this.models.SpinWheelSlices.findAll({ order: [['sort_order', 'ASC']], raw: true });
    return { slices: rows.map((r) => this.#shapeSlice(r, { includeWeight: false })), disabled: false };
  }

  /** @legacy GET /api/spinwin/user/eligibility */
  async eligibility({ userId }) {
    const config = await this.getConfig();
    if (!config?.isActive) return { eligible: false, reason: 'The spin wheel is currently disabled' };

    const last = await this.models.SpinWheelClaims.findOne({
      where: { user_id: userId },
      order: [['claimed_at', 'DESC']],
      raw: true,
    });

    // The first spin is free — no deposit needed.
    if (!last) return { eligible: true, firstSpin: true, nextEligibleAt: null };

    if (config.unlimitedSpin) return { eligible: true, firstSpin: false, nextEligibleAt: null };

    const nextEligibleAt = this.#nextEligibleAt(last.claimed_at, config.claimCooldownDays);
    if (nextEligibleAt > new Date()) {
      return { eligible: false, reason: 'Cooldown active', nextEligibleAt };
    }

    const deposit = await this.#firstDeposit(userId);
    if (!deposit) return { eligible: false, reason: 'Make a deposit to spin again', nextEligibleAt };
    if (money.lt(deposit.amount, config.minDeposit)) {
      return {
        eligible: false,
        reason: `A deposit of at least ${config.minDeposit} is required`,
        nextEligibleAt,
      };
    }

    return { eligible: true, firstSpin: false, depositAmount: deposit.amount, nextEligibleAt };
  }

  /**
   * @legacy POST /api/spinwin/user/claim
   *
   * Spin, and issue the code.
   *
   * The whole thing runs in one transaction with the player's claim history
   * locked, so two simultaneous requests cannot both pass the cooldown.
   */
  async spin({ userId }) {
    const config = await this.getConfig();
    if (!config?.isActive) throw errors.DISABLED();

    const slices = await this.models.SpinWheelSlices.findAll({ order: [['sort_order', 'ASC']], raw: true });
    if (!slices.length) throw errors.NO_SLICES();

    return this.db.transaction(async (transaction) => {
      /**
       * Lock this player's claim history for the duration.
       *
       * `FOR UPDATE` on the SELECT means the second concurrent spin blocks here
       * until the first has committed its new claim row — and then reads it,
       * and fails the cooldown. Without it both read the same last claim.
       *
       * A player with no history locks no rows, which is correct: their first
       * spin is free and there is nothing to serialise against except the
       * insert itself.
       */
      const last = await this.models.SpinWheelClaims.findOne({
        where: { user_id: userId },
        order: [['claimed_at', 'DESC']],
        lock: transaction.LOCK.UPDATE,
        transaction,
        raw: true,
      });

      if (last && !config.unlimitedSpin) {
        const nextEligibleAt = this.#nextEligibleAt(last.claimed_at, config.claimCooldownDays);
        if (nextEligibleAt > new Date()) throw errors.COOLDOWN_ACTIVE({ nextEligibleAt });

        const deposit = await this.#firstDeposit(userId);
        if (!deposit || money.lt(deposit.amount, config.minDeposit)) {
          throw errors.DEPOSIT_REQUIRED({ minimum: config.minDeposit });
        }
      }

      const winIndex = this.#draw(slices);
      const slice = slices[winIndex];
      const rewardPct = String(slice.reward_pct ?? '0');
      const isBadLuck = Boolean(slice.is_bad_luck) || Number(rewardPct) === 0;

      let redeemCode = null;

      if (!isBadLuck) {
        /**
         * One active spin-wheel code at a time. Winning again expires the
         * previous one rather than stacking — otherwise a player in unlimited
         * mode accumulates codes and applies the best one later.
         */
        await this.models.Redeembonus.update(
          { status: CODE_STATUS.EXPIRED, updatedat: new Date() },
          {
            where: { userid: userId, source: CODE_SOURCE, status: CODE_STATUS.ACTIVE },
            transaction,
          }
        );

        redeemCode = await this.#issueCode({ userId, rewardPct, transaction });
      }

      const claim = await this.models.SpinWheelClaims.create(
        {
          user_id: userId,
          // Both zero: the wheel awards a PERCENTAGE applied at deposit time,
          // not a fixed amount. The columns are legacy shape, kept so the
          // existing admin screens still read.
          deposit_amount: '0',
          reward_amount: '0',
          slice_label: slice.label,
          redeem_code: redeemCode,
          claimed_at: new Date(),
        },
        { transaction }
      );

      this.logger?.info({ userId, slice: slice.label, redeemCode, claimId: claim.id }, 'Spin wheel claimed');

      return {
        winIndex,
        slice: this.#shapeSlice(slice, { includeWeight: false }),
        isBadLuck,
        redeemCode,
        // The percentage is applied to the next deposit, so no money moves here.
        rewardPct: isBadLuck ? '0' : rewardPct,
      };
    });
  }

  /** A player's own spin history. */
  async myClaims({ userId, limit = 50, offset = 0 }) {
    return this.listClaims({ userId, limit, offset });
  }

  // ══════════════════════════════════════════════════════════════════════

  /**
   * Pick a slice, weighted, using a source an attacker cannot predict.
   *
   * `crypto.randomInt(total)` gives a uniform integer in [0, total). Walking
   * the cumulative weights maps it onto a slice with exactly the intended
   * probabilities and no floating-point edge at the boundaries — the legacy
   * `rand -= weight; if (rand <= 0)` form makes the FIRST slice slightly more
   * likely than its weight, because a draw of exactly 0 also lands there.
   *
   * A total weight of zero is a configuration error, not something to paper
   * over by silently returning slice 0 — which is what legacy did, turning a
   * misconfigured wheel into one that always lands on the same slice.
   */
  #draw(slices) {
    const weights = slices.map((s) => Math.max(0, Math.trunc(Number(s.weight ?? 0))));
    const total = weights.reduce((sum, w) => sum + w, 0);

    if (total <= 0) throw errors.INVALID_WEIGHTS();

    let roll = crypto.randomInt(total);
    for (let i = 0; i < weights.length; i += 1) {
      if (roll < weights[i]) return i;
      roll -= weights[i];
    }

    // Unreachable: the loop consumes exactly `total`. Present so a future edit
    // that breaks the invariant fails loudly rather than returning undefined.
    throw errors.INVALID_WEIGHTS();
  }

  /**
   * Issue a redeem code.
   *
   * The uniqueness is the database's (migration 013). A collision retries with
   * a fresh code rather than being checked for in advance — the check-then-
   * insert form has a window between the two, which is what legacy did.
   */
  async #issueCode({ userId, rewardPct, transaction, attempt = 0 }) {
    const code = crypto.randomBytes(16).toString('hex').slice(0, CODE_LENGTH).toUpperCase();

    try {
      await this.models.Redeembonus.create(
        {
          userid: userId,
          code,
          // The bonus is a percentage of a future deposit, so there is no
          // amount yet. Zero rather than null because the column is NOT NULL.
          amount: 0,
          status: CODE_STATUS.ACTIVE,
          bonus_pct: rewardPct,
          source: CODE_SOURCE,
          createdat: new Date(),
          updatedat: new Date(),
        },
        { transaction }
      );
      return code;
    } catch (error) {
      if (error?.name === 'SequelizeUniqueConstraintError' && attempt < 5) {
        this.logger?.warn({ attempt }, 'Redeem code collision — retrying');
        return this.#issueCode({ userId, rewardPct, transaction, attempt: attempt + 1 });
      }
      throw error;
    }
  }

  /**
   * The player's FIRST successful deposit, across every gateway.
   *
   * "First", not "largest" and not "most recent" — that is the legacy rule and
   * it has a consequence worth stating: once a player has ever deposited above
   * the minimum, they qualify for every future spin, because the figure being
   * checked never changes. Whether that is intended is a product question; it
   * is preserved here rather than quietly tightened.
   */
  async #firstDeposit(userId) {
    let earliest = null;

    for (const source of DEPOSIT_SOURCES) {
      const row = await this.models[source.model].findOne({
        where: {
          [source.userColumn]: source.userIdIsText ? String(userId) : userId,
          status: source.successValues,
        },
        order: [['created_at', 'ASC']],
        raw: true,
      });
      if (!row) continue;

      const at = new Date(row.created_at ?? 0);
      if (!earliest || at < earliest.at) {
        earliest = { at, amount: money.toDecimalString(money.toMinor(row.amount ?? '0')), source: source.provider };
      }
    }

    return earliest;
  }

  #nextEligibleAt(lastClaimedAt, cooldownDays) {
    const next = new Date(lastClaimedAt);
    next.setUTCDate(next.getUTCDate() + Number(cooldownDays ?? 0));
    return next;
  }

  #shapeConfig(row) {
    return {
      id: row.id,
      minDeposit: money.toDecimalString(money.toMinor(row.min_deposit ?? '0')),
      claimCooldownDays: Number(row.claim_cooldown_days ?? 0),
      isActive: Boolean(row.is_active),
      unlimitedSpin: Boolean(row.unlimited_spin),
    };
  }

  #shapeSlice(row, { includeWeight }) {
    return {
      id: row.id,
      label: row.label,
      rewardPct: String(row.reward_pct ?? '0'),
      color: row.color,
      sortOrder: row.sort_order,
      isBadLuck: Boolean(row.is_bad_luck),
      // Only ever for staff. See publicSlices().
      ...(includeWeight ? { weight: Number(row.weight ?? 0) } : {}),
    };
  }
}

module.exports = { SpinWheelService };
