'use strict';

// AUTO-GENERATED — do not edit by hand.
// casino domain — owned by casino-service (44 tables).

module.exports = {
  Apigames: require('./Apigames'),
  Betoutcome1m: require('./Betoutcome1m'),
  Betoutcome2m: require('./Betoutcome2m'),
  Betoutcome30s: require('./Betoutcome30s'),
  Bets: require('./Bets'),
  Bets1m: require('./Bets1m'),
  Bets2m: require('./Bets2m'),
  Bets30s: require('./Bets30s'),
  Bots: require('./Bots'),
  CrashGames: require('./CrashGames'),
  Crashs: require('./Crashs'),
  GameRuns: require('./GameRuns'),
  GisGameDeletionAudit: require('./GisGameDeletionAudit'),
  GisGames: require('./GisGames'),
  Gisgamesnew: require('./Gisgamesnew'),
  GisPrioritizedGames: require('./GisPrioritizedGames'),
  GisPrioritizedTypes: require('./GisPrioritizedTypes'),
  GisProviders: require('./GisProviders'),
  GisProvidersNew: require('./GisProvidersNew'),
  GisRecentlyPlayed: require('./GisRecentlyPlayed'),
  GisResponseCache: require('./GisResponseCache'),
  GisSessions: require('./GisSessions'),
  GisTransactions: require('./GisTransactions'),
  HotGames: require('./HotGames'),
  House: require('./House'),
  IndianGames: require('./IndianGames'),
  JsGames: require('./JsGames'),
  JsGameSessions: require('./JsGameSessions'),
  JsGameTransactions: require('./JsGameTransactions'),
  LiveCasino: require('./LiveCasino'),
  PopularSlots: require('./PopularSlots'),
  PrioritizedGames: require('./PrioritizedGames'),
  PrioritizedGisGameItemsBackup: require('./PrioritizedGisGameItemsBackup'),
  PrioritizedGisGames: require('./PrioritizedGisGames'),
  ProviderGames: require('./ProviderGames'),
  RemovedPrioritizedGamesAudit: require('./RemovedPrioritizedGamesAudit'),
  Session1m: require('./Session1m'),
  Session2m: require('./Session2m'),
  Session30s: require('./Session30s'),
  TransactionLive: require('./TransactionLive'),
  TransactionSlot: require('./TransactionSlot'),
  Windata1m: require('./Windata1m'),
  Windata2m: require('./Windata2m'),
  Windata30s: require('./Windata30s'),
};
