'use strict';

// AUTO-GENERATED — do not edit by hand.
// core domain — owned by user-service (41 tables).

module.exports = {
  Bonusgame: require('./Bonusgame'),
  Bonushistory: require('./Bonushistory'),
  BonusHistory: require('./BonusHistory'),
  ChatBrazil: require('./ChatBrazil'),
  ChatGlobal: require('./ChatGlobal'),
  ClubEarningsConfigurations: require('./ClubEarningsConfigurations'),
  ClubHierarchy: require('./ClubHierarchy'),
  Clubs: require('./Clubs'),
  Credits: require('./Credits'),
  CreditsLedger: require('./CreditsLedger'),
  Cronbonus: require('./Cronbonus'),
  Exchangerate: require('./Exchangerate'),
  GiftCards: require('./GiftCards'),
  Logs: require('./Logs'),
  Messages: require('./Messages'),
  Notifications: require('./Notifications'),
  Redeembonus: require('./Redeembonus'),
  Rewards: require('./Rewards'),
  SpinWheelClaims: require('./SpinWheelClaims'),
  SpinWheelConfig: require('./SpinWheelConfig'),
  SpinWheelSlices: require('./SpinWheelSlices'),
  SwapHistory: require('./SwapHistory'),
  Team: require('./Team'),
  Tokens: require('./Tokens'),
  Transactions: require('./Transactions'),
  UnlockedRewards: require('./UnlockedRewards'),
  User2fa: require('./User2fa'),
  Userbonus: require('./Userbonus'),
  Userconfig: require('./Userconfig'),
  UserExposures: require('./UserExposures'),
  UserGiftCards: require('./UserGiftCards'),
  UserKyc: require('./UserKyc'),
  UserLoginHistory: require('./UserLoginHistory'),
  UserOtps: require('./UserOtps'),
  Users: require('./Users'),
  Userwager: require('./Userwager'),
  UserwagerHistory: require('./UserwagerHistory'),
  VaultPro: require('./VaultPro'),
  WagerMultiplierCommon: require('./WagerMultiplierCommon'),
  WalletHistory: require('./WalletHistory'),
  Wallets: require('./Wallets'),
};
